# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u8bb0\u5f55\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('first_sl_id', models.IntegerField(default=1, verbose_name='\u6240\u5c5e\u9876\u7ea7\u83dc\u5355id')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
                ('serial_number', models.IntegerField(default=0, verbose_name='\u4f4d\u7f6e\u5e8f\u53f7')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='firstshoppinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u8bb0\u5f55\u65f6\u95f4'),
        ),
    ]
