# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20171218_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstshoppinglist',
            name='serial_number',
            field=models.FloatField(default=0, verbose_name='\u4f4d\u7f6e\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='secondshoppinglist',
            name='serial_number',
            field=models.FloatField(default=0, verbose_name='\u4f4d\u7f6e\u5e8f\u53f7'),
        ),
    ]
