# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20171218_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u8bb0\u5f55\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('father_id', models.IntegerField(default=1, verbose_name='\u6240\u5c5e\u4e8c\u7ea7\u83dc\u5355id')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('serial_number', models.FloatField(default=0, verbose_name='\u4f4d\u7f6e\u5e8f\u53f7')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='secondshoppinglist',
            old_name='first_sl_id',
            new_name='father_id',
        ),
    ]
