# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_auto_20171218_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdshoppinglist',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u540d\u79f0'),
        ),
    ]
